name: Module CI
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    uses: xrobot-org/XRobot/.github/workflows/module-ci.yml@dev
    with:
      xrobot-ref: dev
      libxr-ref: dev
      dependency-ref: refs/heads/dev
      template-args: '[]'
      image: 'ghcr.io/xrobot-org/docker-image-webots:main'
      cmake-options: '-DLIBXR_SYSTEM=webots -DLIBXR_DRIVER=webots -DWEBOTS_HOME=/usr/local/webots'
